Consolidated functionality; 2 options to be tested
Ricochet-Exchange/ricochet-keeper pull request #36
Opened 2022-03-10 21:01 UTC by MrSquiggles13

I commented out a line of code that could replace a whole block but have no way of testing either methods.

2022-03-11 14:39 UTC, mikeghen requested changes

2022-03-11 14:39 UTC, mikeghen commented on dags/blocksec_plugin/contract_interaction_operator.py
> +        if confirmations >= self.confirmations:
self.confirmations needs to be added in the `init` method

2022-03-11 14:39 UTC, mikeghen commented on dags/blocksec_plugin/contract_interaction_operator.py
>      def __init__(self,
add `confirmations=3` as the default, add `self.confirmations = confirmations` into the init method like is done in the EthereumTransactionSensor's `__init__` method

2022-03-11 21:10 UTC, shreyaspapi commented
Tested works fine, safe to merge after #37

2022-03-11 21:10 UTC, shreyaspapi commented
Tested works fine, safe to merge after #37

2022-03-11 21:17 UTC, shreyaspapi approved these changes

2022-03-20 04:43 UTC, MrSquiggles13 commented
Fixed logic of the execute method should be good to go

2022-03-29 20:28 UTC, MrSquiggles13 commented
@mikeghen mind helpin me out bud? I just wanna claim this bounty and be done with it im pretty sure its sound

2022-05-04 14:22 UTC, closed without merging